spring.application.name=E-commerce

spring.datasource.url=jdbc:mysql://localhost:3307/ecommerce_db?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456


spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/docs


spring.jwt.secret = 8f3c1a7e9b2d4c6f5e1a9d3b7c8e2f6a4d9c1b3e7f2a6c8d5e4b1a9f7c3d2e6
spring.jwt.expiration = 900000